name: agent-app
services:
  - name: agent-service
    image:
      registry_type: DOCR
      registry: registry.digitalocean.com
      repository: formation-registry/AGENT_IMAGE_NAME
    envs:
      - key: AGENT_SCRIPT_NAME
        value: main.py # Override this per agent if needed
      - key: API_PORT
        value: "8000"
    http_port: 8000
    routes:
      - path: /
        preserve_path: true
    instance_count: 1
    instance_size_slug: basic-xxs
