name: agent-app
services:
  - name: agent-svc-local
    image:
      registry_type: DOCR
      repository: travel-agent
      tag: latest
    envs:
      - key: AGENT_SCRIPT_NAME
        value: main.py
      - key: API_PORT
        value: "8000"
    http_port: 8000
    routes:
      - path: /
        preserve_path_prefix: true
    instance_count: 1
    instance_size_slug: basic-xxs
